### PR TITLE
Split post process forwarders

### PR DESCRIPTION
**Pull request by chadwhitacre**
For https://github.com/getsentry/sentry/issues/40120.

Ref:

- https://github.com/getsentry/snuba/pull/3250
- https://github.com/getsentry/sentry/pull/39988

### CODE REVIEW

**Review by lynnagara — APPROVED** [review]

**Comment by chadwhitacre** [comment]
We have [red on master](https://github.com/getsentry/sentry/issues/40120#issuecomment-1281452636).

Waiting for green on branch ...

**Comment by chadwhitacre** [comment]
I got "web container is unhealthy" twice on here and @hubertdeng123 has gotten it once so far. Hrm ... 🤔

**Comment by chadwhitacre** [comment]
I tried again and it's healthy, seems gtm. 👍

**Review by ethanhs — APPROVED** [review]

**Review by hubertdeng123 — APPROVED** [review]

**Comment by chadwhitacre** [comment]
@hubertdeng123 reran with 647f55a9627c5264051b0fa54f7885ab7e7bae23 and got green. 👍

**Comment by chadwhitacre** [comment]
Force-merging to get https://github.com/getsentry/self-hosted/issues/1701 back on track. We'll get CI on master.

**Pull request merged**
