### PR TITLE
Fix command called in reset script

### PR DESCRIPTION
**Pull request by stayallive**
Looks like this was missed in #2029, running reset.sh now runs the bash `reset` and just resets the console 😅

### CODE REVIEW

**Comment by hubertdeng123** [comment]
The purpose of this script is actually to run the clean function that lives in the `scripts/_lib.sh` file. Was this something that was unclear? What would you have wanted the functionality to be?

**Comment by stayallive** [comment]
Well yes. But the cmd in the file was “reset” and not “clean”, see the diff. 

So as is it calls “reset” instead of the expected “clean”.

**Comment by hubertdeng123** [comment]
> Well yes. But the cmd in the file was defined as “reset” and not “clean”, see the diff, so the wrong function is called.

There actually isn't a `reset` function in the file. Maybe what might be cleaner is changing clean -> reset in `scripts/_lib.sh`?

**Comment by stayallive** [comment]
Sure, that also works, updated 👍

**Comment by hubertdeng123** [comment]
thanks for catching this @stayallive

**Review by hubertdeng123 — APPROVED** [review]

**Pull request merged**
