### PR TITLE
Create README-zh.md

### PR DESCRIPTION
**Pull request by beyondverage0908**
Add Chinese readme file

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by aminvakil — COMMENTED** [review]
I don't think this is needed.

**Review by RayWP — COMMENTED** [review]
LGTM

**Comment by chadwhitacre** [comment]
@beyondverage0908 @RayWP If we merge this, can we count on you to help us keep it up-to-date as we make other README changes?

**Comment by chadwhitacre** [comment]
We'll also need to get this passing CI, looks like maybe [trailing whitespace](https://github.com/getsentry/self-hosted/actions/runs/7506825557/job/20439101327?pr=2693#step:4:118)?

**Comment by RayWP** [comment]
@chadwhitacre sure. Will do. Appreciate it

**Comment by chadwhitacre** [comment]
Hrm, I think you posted then deleted @RayWP? 🤔

Either way, I'm good to merge this once we clean up the pre-commit check.

**Comment by chadwhitacre** [comment]
> ```
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django.core.cache.backends.memcached.MemcachedCache': Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class
```

https://github.com/getsentry/self-hosted/actions/runs/7571747446/job/20619977561?pr=2693#step:4:4039

Spurious? 🤔

Doesn't fee like it, same in the others:

https://github.com/getsentry/self-hosted/actions/runs/7571747446/job/20619978008?pr=2693#step:4:3841

https://github.com/getsentry/self-hosted/actions/runs/7571747446/job/20619978441?pr=2693#step:4:3841

[Random instance of the word "memcache"](https://github.com/getsentry/sentry/pull/63375) crossing my radar at roughly the same time ... probably not directly related, but maybe?

**Comment by chadwhitacre** [comment]
Rerunning failures ...

**Comment by chadwhitacre** [comment]
Still failing, need to dig deeper.

**Comment by hubertdeng123** [comment]
tests are now passing, precommit needs to be fixed though

**Comment by liukch** [comment]
I use Chinese in my daily life, but the content of this PR looks like it was translated using a translation software, and the quality is very poor, making it difficult to read.

**Comment by BYK** [comment]
@liukch thanks for the feedback! Do you think you can help improve it?

**Comment by liukch** [comment]
I don't think it's necessary to provide Chinese translations, and it would also require a lot of effort to keep them up-to-date.

@BYK  If you really need Chinese translations, please let me know, and I will improve them. However, I cannot guarantee that I can keep them up-to-date in the long future.

**Comment by BYK** [comment]
Then I'm inclined to close this out in favor of #1996. That way we may also think about a more general way for translating our docs. 

Thoughts @aldy505 @hubertdeng123 @chadwhitacre?

**Comment by aldy505** [comment]
> Then I'm inclined to close this out in favor of #1996. That way we may also think about a more general way for translating our docs.
> 
> Thoughts @aldy505 @hubertdeng123 @chadwhitacre?

I'm up for it! Let's focus more on #1996.

**Comment by hubertdeng123** [comment]
I'm also inclined to close this then, if the Chinese quality is not very good.

**Pull request closed without merging**
