### PR TITLE
Cleanup .env{,.custom} handling

### LINKED ISSUE #941: Reference to realpath in install script breaks macOS compatibility
### Version Information

Version: `2.3.1`

### Steps to Reproduce

1. run `./install.sh` on  macOS (`11.2.3`)

### Expected Result

Install script runs successfully.

### Actual Result

Install script immediately fails.

### Logs

What you saw along the way, e.g.:

- `./install/_lib.sh: line 15: realpath: command not found`

### PR DESCRIPTION
**Pull request by chadwhitacre**
Fixes #941, also addresses the suggestion for a README tweak at the very bottom of https://github.com/getsentry/self-hosted/issues/1491#issuecomment-1159076555.

Look good to you, @aminvakil @glensc @Daniel15?

### CODE REVIEW

**Comment by Daniel15** [comment]
This looks good to me!

**Comment by aminvakil** [comment]
I tested this locally on a clean machine (running `./integration-test.sh`) and faced this error:
```
./_integration-test/../install/_lib.sh: line 28: /home/fedora/self-hosted/_integration-test/.env: No such file or directory
```

**Comment by chadwhitacre** [comment]
What's up with CI? 🤔

```
  time="2022-06-23T00:09:18Z" level=warning msg="The \"HEALTHCHECK_INTERVAL\" variable is not set. Defaulting to a blank string."
  time="2022-06-23T00:09:18Z" level=warning msg="The \"HEALTHCHECK_TIMEOUT\" variable is not set. Defaulting to a blank string."
  time="2022-06-23T00:09:18Z" level=warning msg="The \"HEALTHCHECK_RETRIES\" variable is not set. Defaulting to a blank string."
  time="2022-06-23T00:09:18Z" level=warning msg="The \"SNUBA_IMAGE\" variable is not set. Defaulting to a blank string."
  time="2022-06-23T00:09:18Z" level=warning msg="The \"SENTRY_BIND\" variable is not set. Defaulting to a blank string."
  time="2022-06-23T00:09:18Z" level=warning msg="The \"HEALTHCHECK_TIMEOUT\" variable is not set. Defaulting to a blank string."
  time="2022-06-23T00:09:18Z" level=warning msg="The \"HEALTHCHECK_RETRIES\" variable is not set. Defaulting to a blank string."
  error while interpolating services.redis.healthcheck.retries: failed to cast to expected type: strconv.Atoi: parsing "": invalid syntax
```

https://github.com/getsentry/self-hosted/runs/7014638001?check_suite_focus=true#step:4:1313

This isn't a familiar CI flake. Is it authentic?

**Comment by chadwhitacre** [comment]
> Is it authentic?

Yup, and it's downstream of @aminvakil's result:

```
./_integration-test/../install/_lib.sh: line 28: /home/runner/work/self-hosted/self-hosted/_integration-test/.env: No such file or directory
```

https://github.com/getsentry/self-hosted/runs/7096779775?check_suite_focus=true#step:4:1258

**Review by ethanhs — APPROVED** [review]
This looks good! 

Its a shame there isn't a shell linter that reports macOS/linux incompatibilities :/

**Comment by chadwhitacre** [comment]
> a shell linter that reports macOS/linux incompatibilities

Oooooh ... good idea! :)

**Pull request merged**
