### PR TITLE
Updates Redis to 6.2.10

### PR DESCRIPTION
**Pull request by danielhartnell**
Redis patched two CVEs in release `6.2.9`. We would like to update the Sentry container to apply those fixes:

https://github.com/redis/redis/releases/tag/6.2.9

After that release, it looks like they pushed a bug fix in `6.2.10` so it probably makes sense to bump up to that.

If there's anything I can do to help test or evaluate this change, let me know.

### CODE REVIEW

**Review by BYK — APPROVED** [review]

**Review by chadwhitacre — APPROVED** [review]
LGTM but what version are we on in SaaS prod for the record @hubertdeng123?

**Review by hubertdeng123 — APPROVED** [review]

**Comment by chadwhitacre** [comment]
TIL image-mirror. Are we sure that's reflective of what's in SaaS?

**Comment by hubertdeng123** [comment]
ok, let me confirm to be sure. Looks like redis 5.0 image is used for dev and I saw it being pulled in for getsentry tests

**Comment by hubertdeng123** [comment]
Looks like depending on the cluster, we're running either 5.x of 6.x

**Comment by chadwhitacre** [comment]
Sounds good. Ship it! 🚢

**Comment by chadwhitacre** [comment]
Thanks @danielhartnell! :-)

**Pull request merged**
