### PR TITLE
chore(issue-template): ask for machine specification and provide link to security policy

### PR DESCRIPTION
**Pull request by aldy505**
To remove roundtrip of asking people "what's your machine specification look like?"

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by bc-sentry** [comment]
Similar sentiment to @aminvakil.  We can ask for this information, but it would seem to be marginally useful if other users ran into a machine-specific installation or runtime issue.   On the flip side, by adding this field I wouldn't want it to imply to the poster that we will have some ability to try and reproduce their issue on that hardware.  In most cases, we do not have the bandwidth to reproduce issues and make a best effort try to respond with advice and/or transfer the issue to a product-specific team for triage.

**Comment by BYK** [comment]
I propose adding a checkbox saying something like "My system meets [the minimum system requirements](https://develop.sentry.dev/self-hosted/#required-minimum-system-resources) of Sentry"

**Comment by aldy505** [comment]
> I propose adding a checkbox saying something like "My system meets [the minimum system requirements](https://develop.sentry.dev/self-hosted/#required-minimum-system-resources) of Sentry" instead of asking for specs.

That sounds better.

**Comment by aldy505** [comment]
This will be delayed, since I need to remember which of my device did I use to create this PR.....

**Comment by aldy505** [comment]
> @aldy505 you can always do `gh pr checkout 3447` if you use GitHub CLI 😉

I know but I'm too lazy lol. Let me just find my device.

**Comment by aldy505** [comment]
Alright, done. See the preview here https://github.com/getsentry/self-hosted/blob/cbda363095049c53a9d77ed17f5447d1d5f8a7a8/.github/ISSUE_TEMPLATE/problem-report.yml

**Review by BYK — APPROVED** [review]
Awesome 😎

**Pull request merged**
