### PR TITLE
Fix reset.sh docker-compose call

### PR DESCRIPTION
**Pull request by matti**

### CODE REVIEW

**Review by BYK — APPROVED** [review]

**Comment by aminvakil** [comment]
This has been changed in #1179 .

**Review by aminvakil — CHANGES_REQUESTED** [review]
This should detect docker-compose version, some users (I won't say few or many as I have no idea) have migrated to `docker compose > 2.0.0` and definitely not all of them have symlinked `/usr/local/bin/docker-compose` to plugin to make it compatible with this change.

**Comment by chadwhitacre** [comment]
Seems like it's time to teach `reset.sh` about `install/_lib.sh`, or factor out the `dc` stuff and have both source that.

https://github.com/getsentry/self-hosted/blob/28e413c5dd04e1170ee8201dd5e11b9b3165b65d/install/_lib.sh#L33-L36

**Comment by aminvakil** [comment]
I don't think of any particular reason not use the whole `install/_lib.sh`, but maybe later we want to add something to it, which breaks the `reset.sh`, so it's better to just copy `docker-compose` detection from it IMO.

**Comment by matti** [comment]
fyi I am *not* going to do this extra changes, I just fixed the most obvious bug.

**Comment by aminvakil** [comment]
> This should detect docker-compose version, some users (I won't say few or many as I have no idea) have migrated to `docker compose > 2.0.0` and definitely not all of them have symlinked `/usr/local/bin/docker-compose` to plugin to make it compatible with this change.

@matti What part of this you disagree with?

**Comment by matti** [comment]
I don't diasagree with anything - I just wont do anything else for this PR, feel free to do as much as you want.

**Comment by matti** [comment]
I've seen this about 100 times - somebody makes a PR for one thing and somebody in the project starts listing completely unrelated backlog and the the thing itself stays broken

**Comment by aminvakil** [comment]
Fine, thanks, I'll take it from here in #1215 .

**Pull request closed without merging**
