### PR TITLE
Add .idea to .gitignore

### PR DESCRIPTION
**Pull request by spawnia**
Just like `.vscode/tags`, it is unnecessary IDE stuff.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by BYK — APPROVED** [review]

**Review by hubertdeng123 — APPROVED** [review]

**Comment by hubertdeng123** [comment]
Seems like our pr check is failing on builds from outside contributors, I'll need to take a look into this

**Comment by hubertdeng123** [comment]
@spawnia could you merge master in here? That should fix the failing test

**Comment by hubertdeng123** [comment]
oh, interesting how since your root directory is `sentry-self-hosted` the test breaks, since it isn't `self-hosted`

**Comment by spawnia** [comment]
> oh, interesting how since your root directory is `sentry-self-hosted` the test breaks, since it isn't `self-hosted`

Good discovery, I would not know how to fix it though.

**Comment by hubertdeng123** [comment]
going to merge this because CI here should succeed, root directory is of a different name

**Pull request merged**
