### PR TITLE
Enable dynamic sampling

### PR DESCRIPTION
**Pull request by ethanhs**
I'm unsure if we should merge this so close to a new release, but it seems to be relatively low-risk (famous last words haha).

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Have we had any conversation with DS stakeholders about this? Did they think through self-hosted when they built this? What are the implications?

**Comment by hubertdeng123** [comment]
is there a reason why this isn't turned on by default in `getsentry/sentry` in `src/sentry/conf/server.py`?

**Comment by ethanhs** [comment]
I will check with DS people and get answers to both of those.

**Comment by ethanhs** [comment]
I think this may be more complicated, c.f. [this user who enabled it in kubernetes](https://github.com/getsentry/self-hosted/issues/1835#issuecomment-1349928636). I'll close this for now and open an issue to track this.

**Comment by ethanhs** [comment]
Filed https://github.com/getsentry/self-hosted/issues/1866

**Pull request closed without merging**
