### PR TITLE
Revert changes in 3067683f6c0e1c6dd9ceb72cb5155c1dbf3bf501

### PR DESCRIPTION
**Pull request by hubertdeng123**
This made it directly to master...perhaps we are missing some branch protection rules

### CODE REVIEW

**Comment by hubertdeng123** [comment]
> It's because the rules can be silently bypassed by repo admins. We had this issue before 😞

GitHub seems to have a rule now where there is a checkbox for admins to not bypass branch protection rules. That is now enabled so this shouldn't happen again! :)

**Comment by BYK** [comment]
>GitHub seems to have a rule now where there is a checkbox for admins to not bypass branch protection rules. That is now enabled so this shouldn't happen again! :)

That existed for a very long while and there was/is a reason why it was not enabled. I recommend you to uncheck that box before the next release or you're gonna be in for some fun.

This was documented here: https://github.com/getsentry/publish/pull/1496/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L59 but looks like it was missed when the Craft documentation was created. You may wanna ping @asottile-sentry to update the docs accordingly as this is a critical part of the flow.

**Comment by hubertdeng123** [comment]
Thanks for the context, checked with @asottile-sentry and it appears that the bot now has a separate role that bypasses branch protection. So, hopefully the release will go smoothly 😅...only one way to find out

**Comment by BYK** [comment]
Ah, right. Now _that_ came quite a while later and it makes sense. Don't think you'd have any issues with the release then!

**Pull request merged**
