### PR TITLE
Use transactions python consumer

### PR DESCRIPTION
**Pull request by hubertdeng123**
Seems like this is not used in prod, and not extensively tested and may be the reason why the Stats page is not properly showing events that are accepted/filtered/dropped.

### CODE REVIEW

**Review by lynnagara — APPROVED** [review]

**Review by aldy505 — APPROVED** [review]
I'm gonna give it a try in a few hours.

**Comment by hubertdeng123** [comment]
nvm, stats page fix should be here:
https://github.com/getsentry/self-hosted/pull/2909

**Comment by hubertdeng123** [comment]
However, this should still be merged

**Comment by zKoz210** [comment]
I noticed a significant degradation in processing speed. Now events are displayed after an hour. At a measly 400-500 rps

**Comment by hubertdeng123** [comment]
@zKoz210 is this after switching to rust python transactions consumer? Or using the python transactions python consumer?

**Comment by zKoz210** [comment]
After changing to rust, python works for me without any problems.

**Comment by zKoz210** [comment]
@hubertdeng123 I'm still experiencing performance issues with event processing. Every new release I have to roll back Rust and return old workers. Can I somehow help find and solve this problem?

**Comment by zKoz210** [comment]
image

Here you can see how workers worked in Python, then I turned on Rust again and returned Python back

**Comment by hubertdeng123** [comment]
Closing as this PR never resolved the underlying issue it was supposed to, and switching from rust consumers to python consumers is a separate issue

**Pull request closed without merging**
