### PR TITLE
Add a cloudbuild.yaml for GCB

### LINKED ISSUE #1311: Build on GCB during CI
We broke CI in `sentry` and `snuba` with #1251 and #1289, due to (not fully understood) discrepancies in the environment between local dev, `self-hosted` CI, and `sentry`/`snuba` CI. The proposal here is to trigger a GCB runner similar to the ones in `sentry` and `snuba` to run as part of `self-hosted` CI to ensure that we're not breaking CI over there with our changes here. This should cover us in the future even if we don't fully understand the root cause for the problem(s) with #1251 and #1289.

This is an action item for [INC-98](https://getsentry.atlassian.net/browse/INC-98) (private).

### PR DESCRIPTION
**Pull request by chadwhitacre**
Closes #1311.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
GCB is green, slogging through #1171 #1293 #1294 ...

**Comment by BYK** [comment]
Why not go the other way around and replace those GCB runs with GitHub Actions? You can now use OIDC for securely pushing images to Google Cloud: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform

Would be less maintenance and better DX as we all know nobody looks at (or understands) GCB logs 😀

**Review by aminvakil — APPROVED** [review]
If I have understood correctly, this would happen in a private environment where non-employed contributors without access cannot see the logs over there or even if it had been broken or not, but if this helps sentry guys, sure, why not?

**Comment by chadwhitacre** [comment]
Gosh, with 2x the CI builds post-#1290 it's even harder to get a clean build. :-/

**Comment by chadwhitacre** [comment]
> Why not go the other way around and replace those GCB runs with GitHub Actions?

That's not a bad idea, not sure I want to set the plow that deep though since it involves getting buy-in from other teams and this is an action item for a CI incident, I'd like to resolve sooner than later to prevent future bugs from taking down CI.

**Comment by BYK** [comment]
Happy to give you a hand as the GCB config for Sentry itself is already public (along with Snuba and Relay). All I'd need from your end would be setting up OIDC which should be a breeze.

**Comment by chadwhitacre** [comment]
Thanks @BYK. Merging this for now. I don't have bandwidth to drive GCB→GHA right now but if you start making PRs I will try to keep up. 😁

**Pull request merged**
