### PR TITLE
ref: get self-hosted sentry image from ghcr instead of dockerhub

### PR DESCRIPTION
**Pull request by asottile-sentry**

### CODE REVIEW

**Comment by hubertdeng123** [comment]
I'm guessing something similar to https://github.com/getsentry/sentry/pull/61434 can be applied to snuba, relay, and symbolicator too? It would be good to add a todo for getting those onto ghcr for nightly/latest images

Also, I believe this will break the release scripts here:
https://github.com/getsentry/self-hosted/blob/master/scripts/bump-version.sh

**Comment by asottile-sentry** [comment]
> I'm guessing something similar to [getsentry/sentry#61434](https://github.com/getsentry/sentry/pull/61434) can be applied to snuba, relay, and symbolicator too? It would be good to add a todo for getting those onto ghcr for nightly/latest images
> 
> Also, I believe this will break the release scripts here: https://github.com/getsentry/self-hosted/blob/master/scripts/bump-version.sh

that script seems like it should still work?  I think it'll replace `:latest` with `:whatever` -- unless I'm reading it wrong...

**Comment by asottile-sentry** [comment]
> > I'm guessing something similar to [getsentry/sentry#61434](https://github.com/getsentry/sentry/pull/61434) can be applied to snuba, relay, and symbolicator too? It would be good to add a todo for getting those onto ghcr for nightly/latest images
> > Also, I believe this will break the release scripts here: https://github.com/getsentry/self-hosted/blob/master/scripts/bump-version.sh
> 
> that script seems like it should still work? I think it'll replace `:latest` with `:whatever` -- unless I'm reading it wrong...

oh except we don't have the versioned tagged images in `ghcr` -- what do

**Comment by asottile-sentry** [comment]
alright validated the new image works -- will have to finish this some other time

**Pull request closed without merging**
