### PR TITLE
feat: enable user feedback feature

### LINKED ISSUE #2646: Support new Beta User Feedback feature in self-hosted
New User Feedback workflow and JS widget to capture feedback outside of runtime errors (event_id link).

This will allow us have the feature on the Sandbox. And single tenant.

Feature flags:

```
"organizations:user-feedback-ui",
"organizations:user-feedback-ingest",
"organizations:issue-platform",
"organizations:feedback-ingest",
"organizations:feedback-post-process-group",
"organizations:feedback-visible",
```

## Documentation

Product: https://docs.sentry.io/product/user-feedback/
SDK: https://docs.sentry.io/platforms/javascript/user-feedback/

### PR DESCRIPTION
**Pull request by aldy505**
Closes #2646

This is based on https://develop.sentry.dev/feedback-architecture/ and some other stuff that I've used since User Feedback is in beta.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by bruno-garcia** [comment]
Thanks @aldy505 !

**Comment by aliu39** [comment]
Thanks @aldy505! This relates to a PR @hubertdeng123 and I were working on a while back: https://github.com/getsentry/self-hosted/pull/3060. We had some problems getting relay to accept the envelopes when manually testing, something CORS related.

You'll also need the option in https://github.com/getsentry/self-hosted/pull/3061

**Review by BYK — APPROVED** [review]

**Comment by aldy505** [comment]
> Thanks @aldy505! This relates to a PR @hubertdeng123 and I were working on a while back: #3060. We had some problems getting relay to accept the envelopes when manually testing, something CORS related.

@aliu39 How did you guys encounter the CORS issue?

> You'll also need the option in #3061, though we can do that in a separate PR

I don't quite get it why it's not `1.0` yet, since it's GA already...

**Comment by aliu39** [comment]
> > Thanks @aldy505! This relates to a PR @hubertdeng123 and I were working on a while back: #3060. We had some problems getting relay to accept the envelopes when manually testing, something CORS related.
> 
> 
> 
> @aliu39 How did you guys encounter the CORS issue?
> 
> 
> 
> > You'll also need the option in #3061, though we can do that in a separate PR
> 
> 
> 
> I don't quite get it why it's not `1.0` yet, since it's GA already... 

It's been a while so I don't remember the details.. cc @hubertdeng123. I can look into it again later this week

It is 1.0 for our SaaS site, but is 0 for self-hosted since we SH doesn't have the topic which your PR adds.

**Comment by hubertdeng123** [comment]
Thanks for putting this PR up @aldy505. I'll work with @aliu39 and look into this to get this enabled

**Comment by hubertdeng123** [comment]
Testing this locally, but encountering this error:
https://github.com/getsentry/sentry/issues/67412

It appears that hitting http://127.0.0.1:9000/organizations/sentry/feedback/?feedbackSlug=${project_slug}:${feedback_event_id} works. 

However, http://127.0.0.1:9000/organizations/sentry/feedback/ does not.

**Comment by aldy505** [comment]
> Testing this locally, but encountering this error: [getsentry/sentry#67412](https://github.com/getsentry/sentry/issues/67412)
> 
> It appears that hitting [http://127.0.0.1:9000/organizations/sentry/feedback/?feedbackSlug=${project_slug}:${feedback_event_id}](http://127.0.0.1:9000/organizations/sentry/feedback/?feedbackSlug=$%7Bproject_slug%7D:$%7Bfeedback_event_id%7D) works.
> 
> However, http://127.0.0.1:9000/organizations/sentry/feedback/ does not.

It's an old known bug. Do you want to wait for the fix for it before we add the feature into SH?

**Comment by aliu39** [comment]
`feedback-ingest`
`feedback-post-process-group`
Found out these flags are needed for [issues platform](https://develop.sentry.dev/issue-platform/) and should be added to this PR. 

We still need to some time to debug the new topic, but it's not needed to enable this feature. To add this feature, technically all we need are the feature flags (can keep the option at 0.0). 

It'd definitely be nice to fix the frontend bug. We're making progress! I think you can merge this PR independent of that, though.

**Comment by aldy505** [comment]
> `feedback-ingest` `feedback-post-process-group` Found out these flags are needed for [issues platform](https://develop.sentry.dev/issue-platform/) and should be added to this PR.

Are you sure you're specifying the right flag? There's no such flag as that on [features/temporary.py](https://github.com/getsentry/sentry/blob/master/src/sentry/features/temporary.py) and [features/permanent.py](https://github.com/getsentry/sentry/blob/master/src/sentry/features/permanent.py). The feature is working as intended on my side, testing it on my development environment (an actual server) using JS SDK v8.

> We still need to some time to debug the new topic, but it's not needed to enable this feature. To add this feature, technically all we need are the feature flags (can keep the option at 0.0).

The topic should be created automatically though, see https://github.com/getsentry/self-hosted/pull/3121

**Comment by aliu39** [comment]
Yeah the topic is created but we were having some problems ingesting thru it.

The flags are right, they are programmatically generated by a feature handler

**Comment by hubertdeng123** [comment]
> It'd definitely be nice to fix the frontend bug. We're making progress! I think you can merge this PR independent of that, though.

@aldy505 Did you encounter the bug that I was facing when testing the feature? I'm wondering if all users running user feedback are experiencing the issue or just me. If all users are facing the issue, then I'd like to avoid merging for now.

**Comment by aldy505** [comment]
> > It'd definitely be nice to fix the frontend bug. We're making progress! I think you can merge this PR independent of that, though.
> 
> 
> 
> @aldy505 Did you encounter the bug that I was facing when testing the feature? I'm wondering if all users running user feedback are experiencing the issue or just me. If all users are facing the issue, then I'd like to avoid merging for now. 

@hubertdeng123 Yeah I'm encountering it. But I since I kind of want the feature and ingestion is not a problem, so I think it's still acceptable.

**Comment by TheDevMinerTV** [comment]
From my tests, using the embed (triggered by `Sentry.showReportDialog()`) works, but using `Sentry.captureFeedback()` doesn't. There's nothing being logged that it isn't working, but the User Feedback tab in an issue also doesn't show anything.

**Comment by aldy505** [comment]
An update: This PR didn't work. Seems like we need to postpone this one a bit.😢 

@TheDevMinerTV said on Discord, that using `Sentry.showReportDialog()` from the JS SDK works. This function doesn't submit the feedback event through the regular envelope. Submitting through the envelope via `Sentry.captureFeedback()` and `Sentry.feedbackIntegration()` didn't work. I only tested with `Sentry.captureFeedback()` and `Sentry.feedbackIntegration()`, both didn't work.

What works so far:
- The topic is created as expected. So no issue on Kafka topic creation.
- The `ingest-feedback` consumer group is correctly consuming `ingest-feedback-events` topic.
- Relay correctly produces feedback event to the `ingest-feedback-events` topic.

I can't check whether the events are correctly ingested to Postgres/Clickhouse since I don't know how to check that.

The feature flags `organizations:user-feedback-spam-filter-ingest` and `organizations:user-feedback-spam-filter-actions` turns out calls to a function/service that requires LLM object to be set up. I think we need to remove these. Exception from the `worker` container (thanks @TheDevMinerTV):
```
worker-1 | Traceback (most recent call last):
worker-1 |   File "/usr/src/sentry/src/sentry/feedback/usecases/create_feedback.py", line 197, in create_feedback_issue
worker-1 |     is_message_spam = is_spam(event["contexts"]["feedback"]["message"])
worker-1 |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1 |   File "/usr/src/sentry/src/sentry/utils/metrics.py", line 229, in inner
worker-1 |     return f(*args, **kwargs)
worker-1 |            ^^^^^^^^^^^^^^^^^^
worker-1 |   File "/usr/src/sentry/src/sentry/feedback/usecases/spam_detection.py", line 36, in is_spam
worker-1 |     response = complete_prompt(
worker-1 |                ^^^^^^^^^^^^^^^^
worker-1 |   File "/usr/src/sentry/src/sentry/llm/usecases/__init__.py", line 75, in complete_prompt
worker-1 |     usecase_config = get_usecase_config(usecase.value)
worker-1 |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1 |   File "/usr/src/sentry/src/sentry/llm/usecases/__init__.py", line 90, in get_usecase_config
worker-1 |     raise InvalidUsecaseError(
worker-1 | sentry.llm.exceptions.InvalidUsecaseError: LLM usecase options not found. please check llm.usecases.options
worker-1 | 19:17:48 [ERROR] sentry.feedback.usecases.create_feedback: Error checking if message is spam
```

Removing both `feedback-spam` flags didn't fix the issue that feedback isn't showing though. (Although I know every one of us live on a very different timezones)

What me and @TheDevMinerTV tried:
- Setting `SENTRY_OPTIONS["feedback.ingest-topic.rollout-rate"]` to `0` instead of `1.0`. Didn't work.

@aliu39 @hubertdeng123 Let me know if you guys want to create a debug session with us for this.

**Comment by aliu39** [comment]
Thanks so much for debugging in-depth @aldy505 @TheDevMinerTV. Good call on removing the spam flags! There are extra settings for that feature not supported in SH yet. 

Hubert and I are in US Pacific time (PST). I'll try the tests you mentioned and see if I reproduce the same result.

**Comment by aldy505** [comment]
I'm going to prioritize something else, until we can finally have the time to debug all this.

**Comment by bruno-garcia** [comment]
Related? 
* https://github.com/getsentry/sentry/issues/70136

**Comment by aldy505** [comment]
Since https://github.com/getsentry/sentry/commit/ee95b681954302b918f53d3fcd423ec50a0699b0 is included in 24.7.1, I'm gonna debug everything this weekend. Go to #self-hosted channel on Discord to see me (potentially) spamming everything about User Feedback.

**Comment by aldy505** [comment]
Debugging update (not really an update since this is not a progress at all):

So everything is correctly working during: 
1. Event sent to Relay
2. Relay then published to "ingest-feedback-events"
3. A Sentry consumer eats "ingest-feedback-events", convert the payload into "occurrences" object and throw it back to Kafka to "ingest-occurrences" (this bit is on the `create_feedback_issue` function) 
4. Then another Sentry consumer should eat "ingest-occurrences", and push it to Arroyo, then it's pushed to some topic that I don't know, consumed again by Snuba and finally insert into Clickhouse to some table that I don't know. At this point, I'm in the blind.

This is the Kafka payload on `ingest-occurrences` topic:  https://pastebin.com/ywnedhwi

I have no idea on how this `ingest-occurrences` consumer works. But I can see my event_id of `62386ca702324ad7b9fada27c4b20379` on  `outcomes_raw_local` table.

```
SELECT *
FROM outcomes_raw_local
WHERE (project_id = 49) AND (event_id = '62386ca7-0232-4ad7-b9fa-da27c4b20379')

┌─org_id─┬─project_id─┬─key_id─┬───────────timestamp─┬─category─┬─outcome─┬─reason─┬─quantity─┬─event_id─────────────────────────────┬─size─┐
│      1 │         49 │   ᴺᵁᴸᴸ │ 2024-07-29 05:45:48 │       14 │       0 │ ᴺᵁᴸᴸ   │        1 │ 62386ca7-0232-4ad7-b9fa-da27c4b20379 │    0 │
└────────┴────────────┴────────┴─────────────────────┴──────────┴─────────┴────────┴──────────┴──────────────────────────────────────┴──────┘
```

So on Clickhouse, that project_id + event_id combination only exists on the `outcomes_raw_local` table. I don't know whether this is a good sign or not.

And... now I'm stuck.

**Comment by aliu39** [comment]
Hi @aldy505 , I'm looking into this now. The issue platform system isn't owned by us so my knowledge goes about as far as you, between ingest-occurrences and Clickhouse. I can try asking some people from that team though.

Just curious, why are you looking at the `outcomes_raw` table and how did you find it?

**Comment by aliu39** [comment]
The correct table is `search_issues_local`, though it's interesting you got the same event id in outcomes 🤔🤔. I'm able to repro all the steps you did but my `search_issues_local` table ends up empty. So seems it seems like something's broken in the occurrence consumer.

Btw, I sent you a friend request on discord, feel free to reach out there if it's more convenient!

**Comment by aliu39** [comment]
Also this didn't solve the issue for me, but remember to add the `feedback-ingest` organizations flag, it's very important. Sorry for all these extra ones

**Comment by aldy505** [comment]
> The correct table is `search_issues_local`, though it's interesting you got the same event id in outcomes 🤔🤔. 

Ok so weird thing is.. the data showed up `search_issues_v2_local`..

**Comment by aldy505** [comment]
Okay so it finally works on my instance. Can you guys also try it out?

**Review by aliu39 — APPROVED** [review]
Working on my end too!

**Review by TheDevMinerTV — COMMENTED** [review]
Seems to work fine for me as well (can't approve because of GitHub permissions), just the frontend is crashing sometimes, but that doesn't belong here.

**Review by hubertdeng123 — APPROVED** [review]
code looks fine to me, although I have not tested this code locally

**Comment by aliu39** [comment]
> Seems to work fine for me as well (can't approve because of GitHub permissions), just the frontend is crashing sometimes, but that doesn't belong here.

@TheDevMinerTV what kind of crashes are you experiencing?

**Pull request merged**
