### PR TITLE
do not use gosu for snuba-transactions-cleanup and snuba-cleanup

### PR DESCRIPTION
**Pull request by goganchic**
Fixes https://github.com/getsentry/self-hosted/issues/1556

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by aminvakil** [comment]
`gosu` has been removed from Dockerfile because sunba Dockerfile is using `USER snuba` at the end of Dockerfile, so there isn't a need to install `gosu` again.

I would say remove `gosu` from commands in `docker-compose.yml` instead of adding `gosu` again.

**Comment by aminvakil** [comment]
I could reproduce the issue (#1556) and also could verified removing `gosu` fixed the problem.

@goganchic Do you want to change your PR to the solution I've said?

**Comment by goganchic** [comment]
Ok, I'll try.

**Comment by goganchic** [comment]
I've checked you suggestion locally: everything works fine. Changed PR as you said.

**Review by aminvakil — APPROVED** [review]
Thanks for fixing this!

**Review by BYK — APPROVED** [review]

**Pull request merged**
