### PR TITLE
Revert "Add CI compose version 1.29.2 / 2.2.3"

### PR DESCRIPTION
**Pull request by chadwhitacre**
Reverts getsentry/self-hosted#1251

We're seeing a failure on an internal CI build that seems to be caused by this, still investigating ...

### CODE REVIEW

**Review by billyvg — APPROVED** [review]
Sentry CI started failing ~10 minutes after this was merged (https://github.com/getsentry/sentry/commit/910073d020488de460d9d0ed264765b298adb9f9)

Checking out the previous `self-hosted` commit in https://github.com/getsentry/sentry/pull/31326 shows the e2e tests passing

**Comment by chadwhitacre** [comment]
Hrm ... restarting CI here (#1171?) ...

**Comment by chadwhitacre** [comment]
Force-merging while we continue debugging.

**Comment by aminvakil** [comment]
Can I help in this or is this part of your internal CI?

**Comment by chadwhitacre** [comment]
The `sentry` CI breakage is happening in Google Cloud Build which you probably won't have too much visibility into, but you can at least help on https://github.com/getsentry/self-hosted/pull/1273 if you're up for it.  I'm trying to get back there myself ...

**Pull request merged**
