### PR TITLE
Update set-up-and-migrate-database.sh

### PR DESCRIPTION
**Pull request by drmrbrewer**
It's `docker-compose` not `docker compose`

### CODE REVIEW

**Comment by BYK** [comment]
It _is_ `docker compose` since a while ago 🙂: https://docs.docker.com/compose/cli-command/

**Comment by drmrbrewer** [comment]
@BYK Oh 🤦‍♂️ but I get:

    # docker compose run --rm web createuser
    unknown flag: --rm
    See 'docker --help'.

**Comment by BYK** [comment]
@drmrbrewer we do have some version detection code around which then defines a `$dc_base` here: https://github.com/getsentry/self-hosted/blob/master/install/dc-detect-version.sh

I think you can make this file use `$dc_base` instead of `docker compose` directly and that should take case of the issue?

**Review by BYK — APPROVED** [review]

**Comment by BYK** [comment]
@chadwhitacre nudge

**Review by chadwhitacre — APPROVED** [review]

**Review by chadwhitacre — APPROVED** [review]

**Comment by chadwhitacre** [comment]
Thanks @drmrbrewer @BYK! :)

**Comment by chadwhitacre** [comment]
I like this PR so much I approved it twice. 🤩

**Comment by drmrbrewer** [comment]
I am sure this will go down as a significant day in the history of self-hosted sentry.  This was the equivalent of laying down a single mosaic tile (or maybe two!) in a luxurious Roman palace.  Well, Rome wasn't built in a day, as they say!

**Pull request merged**
