### PR TITLE
Mandate minimum requirements for ram/cpu

### PR DESCRIPTION
**Pull request by hubertdeng123**
get rid of soft requirements for ram/cpu, enforce this as a hard requirement instead.
16 GB of ram, 4 CPU cores

### CODE REVIEW

**Review by joshuarli — APPROVED** [review]

**Review by IanWoodard — APPROVED** [review]

**Comment by BYK** [comment]
Would be great to record the reasoning for this change somewhere

**Comment by lukasleitsch** [comment]
I'm using a server (Hetzner) with 16GB of RAM, but a few MB are missing. The install script fails with:

```
FAIL: Required minimum RAM available to Docker is 15900 MB, found 15611 MB
```

Would be great to decrease the limit a little bit.

**Comment by danilogco** [comment]
@joshuarli is it possible to reduce the limit? Just like @lukasleitsch, my instance hosted in AWS it's supposed to be 16GB of RAM, but it's a little below of the imposed limit. Well, I changed the file manually inside the EC2 to make it work.

**Comment by joshuarli** [comment]
Yes, sorry. Thanks for the feedback! https://github.com/getsentry/self-hosted/pull/3290

**Pull request merged**
