### PR TITLE
See Replay break

### PR DESCRIPTION
**Pull request by chadwhitacre**
Follow-up to #1990 to see Replay tests fail when they should.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
@JoshFerge Why is c9d262f7c68a38325871ef169793398b94b93d04 [not breaking CI](https://github.com/getsentry/self-hosted/actions/runs/4297539499/jobs/7490892664#step:5:3091)? 🤔

**Comment by JoshFerge** [comment]
@chadwhitacre will take a look. seems like the test is not running? 🤔

**Comment by JoshFerge** [comment]
i also assume the failing test is unrelated?

**Comment by hubertdeng123** [comment]
yeah that one is flaky

**Comment by hubertdeng123** [comment]
closing since we put a pause on replay integration tests
https://github.com/getsentry/self-hosted/issues/2015

**Pull request closed without merging**
