### PR TITLE
ref: span normalization allowed host config

### PR DESCRIPTION
**Pull request by aldy505**
Waiting for PR on `sentry` to be merged first: https://github.com/getsentry/sentry/pull/74195

Relay PR: https://github.com/getsentry/relay/pull/3813
Feature request issues: https://github.com/getsentry/relay/issues/3572 and https://github.com/getsentry/relay/issues/3573

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by Barsoomx** [comment]
For those who jumped on enabling this today(don't):
https://github.com/getsentry/relay/issues/3936

**Comment by aldy505** [comment]
> For those who jumped on enabling this today(don't): [getsentry/relay#3936](https://github.com/getsentry/relay/issues/3936)

:laughing: Sorry about that!

**Comment by Barsoomx** [comment]
For those who did that anyway and trying to revert but relay keeps fetching the old config:

(resetting/changing the option in sentry.conf.py keeps it in cache and the errors continue)

```
relay-1  | {"timestamp":"2024-08-16T08:09:43.045065Z","level":"ERROR","message":"Error deserializing global config option: relay_dynamic_config::global::Options","error":"expected `,` or `}` at line 1 column 24783","target":"relay_dynamic_config::global","filename":"relay-dynamic-config/src/global.rs","line_number":365}
relay-1  | {"timestamp":"2024-08-16T08:09:43.045271Z","level":"ERROR","message":"failed to fetch global config from upstream","error":"could not send request","target":"relay_server::services::global_config","filename":"relay-server/src/services/global_config.rs","line_number":337}
```

Do this:
```
docker exec -ti sentry-web-1 bash
```

```
from sentry import options
options.get("relay.span-normalization.allowed_hosts")
```
Verify it's set to your "broken" value 
```
>>> options.get("relay.span-normalization.allowed_hosts")
['cloudflarestorage.com', 'yourdomain.com']
```

Then you can delete it so it's reset on next call
```
>>> options.delete("relay.span-normalization.allowed_hosts")
True
>>> options.get("relay.span-normalization.allowed_hosts")
[]
```

Now relay should fetch the correct config:
```
relay-1  | {"timestamp":"2024-08-16T08:12:54.213680Z","level":"INFO","message":"received global config from upstream","target":"relay_server::services::global_config","filename":"relay-server/src/services/global_config.rs","line_number":317}
```

**Comment by aldy505** [comment]
@Barsoomx the fix is merged and available on Dockerhub if you want to try it. I'm going to try this in a few hours. 

Use this tag for relay: getsentry/relay:87357fb5e50c9e7e47111709b8a345e778231961 (link: https://hub.docker.com/layers/getsentry/relay/87357fb5e50c9e7e47111709b8a345e778231961/images/sha256-b3ab1bc8336c318d540a610fa2b884ba482f7e252c7b2a14a8129c0f6756afd3?context=explore)

**Comment by aldy505** [comment]
@hubertdeng123 tested on my instance

**Review by hubertdeng123 — APPROVED** [review]

**Pull request merged**
