### PR TITLE
Handle missing example files gracefully

### PR DESCRIPTION
**Pull request by chadwhitacre**
We're seeing [a bit of noise](https://self-hosted.getsentry.net/organizations/self-hosted/issues/246/) in our dogfooding instance from cases where it seems folks have mucked with the example files we expect to exist. Let's give a more specific error message in this case and avoid reporting to dogfooding.

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Expecting e186a79548cd6ec13d44a6b73340984ac7ed7d60 to fail with a generic error.

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/self-hosted/actions/runs/4067040190/jobs/7003897054#step:5:173

```
Ensuring Relay credentials ...
  Creating ../relay/config.yml...
  cp: cannot stat '../relay/config.example.yml': No such file or directory
  Error in ./install/_lib.sh:48.
  'cp -n $(echo "$1" | sed 's/\.[^.]*$/.example&/') "$1"' exited with status 1
  yes: standard output: Broken pipe
  yes: standard output: Broken pipe
  yes: standard output: Broken pipe
  -> ./install.sh:main:26
  --> ensure-relay-credentials.sh:source:6
  ---> ./install/_lib.sh:ensure_file_from_example:48
```

**Comment by chadwhitacre** [comment]
I confirmed that an exit in a function exits the whole script, with default 0 ofc.

**Comment by chadwhitacre** [comment]
Getting the "Oops!" but the test is still red. 🤔

https://github.com/getsentry/self-hosted/actions/runs/4067238068/jobs/7004344020#step:5:174

**Comment by chadwhitacre** [comment]
I'm expecting to see the "Oops!" and then the integration-test.sh terminates.

**Comment by chadwhitacre** [comment]
[Boom](https://github.com/getsentry/self-hosted/actions/runs/4067718476/jobs/7005404979#step:5:176)!

```
  Oops! Where did ../relay/config.example.yml go? 🤨 We need it in order to create ../relay/config.yml.
  Error: Process completed with exit code 42.
  ##[debug]Finishing: Integration Test
```

Okay, ready for review.

**Review by hubertdeng123 — APPROVED** [review]

**Pull request merged**
