### PR TITLE
ref: Move most consumers to unified consumer CLI

### PR DESCRIPTION
**Pull request by untitaker**
Context: https://github.com/getsentry/sentry/pull/50364

### CODE REVIEW

**Comment by BYK** [comment]
```
KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: profiles: Broker: Unknown topic or partition"}
```

This is from profiles consumer. There might be others, check the logs for more 🙂

**Comment by untitaker** [comment]
thank byk for helping out here!

> KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Subscribed topic not available: profiles: Broker: Unknown topic or partition"}

The problem is, I am not even changing the topic here -- the old CLI is also depending on the same topic.

if I understand it right, this script was supposed to create those topics anyway: https://github.com/getsentry/self-hosted/blob/a52de4ab1bdb6e1cc2d33b8c0f72414b28d48649/install/create-kafka-topics.sh#L1

**Comment by hubertdeng123** [comment]
seems odd that the integration test on docker compose v2.0.1 is succeeding 🤔

**Comment by hubertdeng123** [comment]
now it's passing, for the record I've never seen that error before and it should not have failed twice in a row

**Review by hubertdeng123 — APPROVED** [review]
🚀🚀

**Pull request merged**
