### PR TITLE
Remove cdc and wal2json and use the default postgres entrypoint

### PR DESCRIPTION
**Pull request by beezz**
CDC and wal2json in no longer used and has been removed in prod long time ago. This PR attempts to remove all the traces of cdc and wal2json from self-hosted setup possibly using the default postgresql docker entrypoint . 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by BYK** [comment]
Yes, thanks for doing this!

Not sure if you were able to dig it out yourself but here's when all this stuff was introduced: #938.

Looks like we need a removal from the `.env` file too?

**Comment by beezz** [comment]
> Yes, thanks for doing this!
> 
> Not sure if you were able to dig it out yourself but here's when all this stuff was introduced: #938.
> 
> Looks like we need a removal from the `.env` and `.gitignore` files too?
> 
> Oh, and the `init_hba` file

Thanks for quick response! I removed the last bits 👍

**Comment by BYK** [comment]
> Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/runner/work/self-hosted/self-hosted/self-hosted/postgres
  Error in install/set-up-and-migrate-database.sh:4.
  
Hmm, let's see why that is

**Comment by BYK** [comment]
Looks like this needs to go too: https://github.com/getsentry/self-hosted/blob/053f4010b61adf4677d8ac81488d41dd95461fba/docker-compose.yml#L140-L145

**Comment by beezz** [comment]
> Looks like this needs to go too:
> 
> https://github.com/getsentry/self-hosted/blob/053f4010b61adf4677d8ac81488d41dd95461fba/docker-compose.yml#L140-L145

oh, thanks! Removed the read only bind as well now.

**Review by hubertdeng123 — APPROVED** [review]

**Pull request merged**
